name: smart_business_card
description: A smart business card system with QR code scanning, calendar integration, and team management.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.6.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  lucide_icons: 
  url_launcher: ^6.2.2
  intl: ^0.19.0
  flutter_map: ^6.1.0
  latlong2: 
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/