plugins = []
headers = []
redirects = [
  { from = "/*", to = "/index.html", status = 200 }
]

[functions]

[functions."*"]

[build]
publish = "/Users/ajaydahal/Downloads/older/busy_man/astrologer-website/dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/Users/ajaydahal/Downloads/older/busy_man/astrologer-website"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]