import { Navigation } from '../../components/Navigation'
import { Footer } from '../../components/Footer'
import { useState } from 'react'
import { useBookingMutations } from '../../features/booking/presentation/hooks/booking.hooks'
import type { BookingEntity } from '../../features/booking/domain/entities/booking.entity'
import NepaliDate from 'nepali-date-converter'

export function BookingPage() {
  const { add } = useBookingMutations()
  const [formData, setFormData] = useState({
    name: '',
    phone: '',
    email: '',
    serviceTypes: [] as string[],
    nepaliDate: new NepaliDate().format('YYYY/MM/DD'),
    location: '',
    description: ''
  })

  const services = [
    'Kundali / Horoscope Consultation',
    'Vastu Consultation',
    'Shraddha / Ritual Guidance',
    'Puja Consultation',
    'Marriage/Date/Muhurat Consultation',
    'General Astrology Consultation'
  ]

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    
    const booking: BookingEntity = {
      id: '', // Will be generated by Firestore
      name: formData.name,
      phone: formData.phone,
      email: formData.email,
      serviceType: formData.serviceTypes.join(', '),
      nepaliDate: formData.nepaliDate,
      location: formData.location,
      description: formData.description,
      status: 'Pending',
    }

    add.mutate(booking, {
      onSuccess: () => {
        alert('Booking request submitted successfully! I will contact you shortly.')
        setFormData({
          name: '',
          phone: '',
          email: '',
          serviceTypes: [],
          nepaliDate: '',
          location: '',
          description: ''
        })
      },
      onError: (error) => {
        alert(`Failed to submit booking: ${error.message}`)
      }
    })
  }

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    })
  }

  const toggleService = (service: string) => {
    setFormData(prev => ({
      ...prev,
      serviceTypes: prev.serviceTypes.includes(service)
        ? prev.serviceTypes.filter(s => s !== service)
        : [...prev.serviceTypes, service]
    }))
  }

  return (
    <div className="min-h-screen flex flex-col bg-cosmic-950 font-body">
      <Navigation />
      <main className="flex-1 py-24 relative overflow-hidden">
        <div className="absolute inset-0 bg-cosmic-gradient opacity-50"></div>
        <div className="absolute inset-0 bg-sacred-pattern"></div>
        
        <div className="relative z-10 container mx-auto px-4 max-w-3xl">
          <div className="text-center mb-12">
            <div className="w-20 h-20 mx-auto mb-8 relative">
              <div className="absolute inset-0 bg-gradient-to-br from-gold-400 to-gold-600 rounded-full animate-glow opacity-60 blur-xl"></div>
              <div className="relative w-full h-full bg-gradient-to-br from-gold-400 to-gold-600 rounded-full flex items-center justify-center text-cosmic-950 text-3xl font-display font-bold">
                ॐ
              </div>
            </div>
            <h1 className="text-5xl md:text-6xl font-display font-bold mb-4 text-gold-400">Book an Appointment</h1>
            <p className="text-xl text-amber-200/70">
              Fill out the form below to request an appointment
            </p>
          </div>

          <div className="bg-cosmic-800/40 backdrop-blur-sm p-8 rounded-2xl border border-gold-400/20">
            <form onSubmit={handleSubmit} className="space-y-6">
              <div>
                <label htmlFor="name" className="block text-sm font-medium mb-2 text-amber-100">
                  Full Name *
                </label>
                <input
                  type="text"
                  id="name"
                  name="name"
                  required
                  value={formData.name}
                  onChange={handleChange}
                  className="w-full px-4 py-3 border border-gold-400/30 rounded-lg bg-cosmic-900/50 text-amber-100 placeholder-amber-200/40 focus:border-gold-400 focus:outline-none transition-colors"
                  placeholder="Your full name"
                />
              </div>

              <div>
                <label htmlFor="phone" className="block text-sm font-medium mb-2 text-amber-100">
                  Phone Number *
                </label>
                <input
                  type="tel"
                  id="phone"
                  name="phone"
                  required
                  value={formData.phone}
                  onChange={handleChange}
                  className="w-full px-4 py-3 border border-gold-400/30 rounded-lg bg-cosmic-900/50 text-amber-100 placeholder-amber-200/40 focus:border-gold-400 focus:outline-none transition-colors"
                  placeholder="Your phone number"
                />
              </div>

              <div>
                <label htmlFor="email" className="block text-sm font-medium mb-2 text-amber-100">
                  Email (Optional)
                </label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                  className="w-full px-4 py-3 border border-gold-400/30 rounded-lg bg-cosmic-900/50 text-amber-100 placeholder-amber-200/40 focus:border-gold-400 focus:outline-none transition-colors"
                  placeholder="Your email address"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-3 text-amber-100">
                  Service Types * (Select one or more)
                </label>
                <div className="flex flex-wrap gap-3">
                  {services.map(service => (
                    <button
                      key={service}
                      type="button"
                      onClick={() => toggleService(service)}
                      className={`px-4 py-2 rounded-full font-display font-medium transition-all duration-300 ${
                        formData.serviceTypes.includes(service)
                          ? 'bg-gradient-to-r from-gold-500 to-gold-600 text-cosmic-950 shadow-lg shadow-gold-400/20'
                          : 'bg-cosmic-900/50 border border-gold-400/30 text-amber-100 hover:border-gold-400 hover:bg-gold-400/10'
                      }`}
                    >
                      {service}
                    </button>
                  ))}
                </div>
                {formData.serviceTypes.length === 0 && (
                  <p className="text-sm text-gold-400/70 mt-2">Please select at least one service</p>
                )}
              </div>

              <div>
                <label htmlFor="nepaliDate" className="block text-sm font-medium mb-2 text-amber-100">
                  Nepali Date (BS) *
                </label>
                <input
                  type="text"
                  id="nepaliDate"
                  name="nepaliDate"
                  required
                  value={formData.nepaliDate}
                  onChange={handleChange}
                  placeholder="e.g., 2081/05/12"
                  className="w-full px-4 py-3 border border-gold-400/30 rounded-lg bg-cosmic-900/50 text-amber-100 placeholder-amber-200/40 focus:border-gold-400 focus:outline-none transition-colors"
                />
                <p className="text-xs text-amber-200/50 mt-1">Format: YYYY/MM/DD (Bikram Sambat) - Default is today's date</p>
              </div>

              <div>
                <label htmlFor="location" className="block text-sm font-medium mb-2 text-amber-100">
                  Location *
                </label>
                <input
                  type="text"
                  id="location"
                  name="location"
                  required
                  value={formData.location}
                  onChange={handleChange}
                  placeholder="e.g., Biratnagar, Office, or Online"
                  className="w-full px-4 py-3 border border-gold-400/30 rounded-lg bg-cosmic-900/50 text-amber-100 placeholder-amber-200/40 focus:border-gold-400 focus:outline-none transition-colors"
                />
              </div>

              <div>
                <label htmlFor="description" className="block text-sm font-medium mb-2 text-amber-100">
                  Additional Details / Message
                </label>
                <textarea
                  id="description"
                  name="description"
                  rows={4}
                  value={formData.description}
                  onChange={handleChange}
                  className="w-full px-4 py-3 border border-gold-400/30 rounded-lg bg-cosmic-900/50 text-amber-100 placeholder-amber-200/40 focus:border-gold-400 focus:outline-none transition-colors resize-none"
                  placeholder="Any additional information about your consultation needs"
                />
              </div>

              <button
                type="submit"
                disabled={formData.serviceTypes.length === 0}
                className="w-full bg-gradient-to-r from-gold-500 to-gold-600 text-cosmic-950 px-6 py-4 rounded-lg font-display font-semibold hover:shadow-2xl hover:shadow-gold-400/30 hover:scale-105 transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
              >
                Submit Booking Request
              </button>
            </form>

            <div className="mt-6 p-4 bg-cosmic-900/50 rounded-lg border border-gold-400/20">
              <p className="text-sm text-amber-200/70">
                <strong className="text-gold-400">Note:</strong> Your booking request will be reviewed. 
                You will receive confirmation via phone or email once your appointment is approved.
              </p>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}
