import { Navigation } from '../../../../components/Navigation'
import { Footer } from '../../../../components/Footer'
import { useTranslation } from 'react-i18next'
import { useState, useMemo } from 'react'
import { useBookingList, useBookingMutations } from '../../../booking/presentation/hooks/booking.hooks'
import { NepaliDatePickerCustom } from '../../../../components/NepaliDatePickerCustom'
import type { BookingEntity } from '../../../booking/domain/entities/booking.entity'
import NepaliDate from 'nepali-date-converter'
import { useServiceList } from '../../../service/presentation/hooks/service.hooks'

export function CalendarPage() {
  const { t } = useTranslation()
  const { data: bookingsData, isLoading, error } = useBookingList()
  const { data: services } = useServiceList()
  const { add } = useBookingMutations()

  const serviceNames = services?.map(s => s.titleEn) || []

  // Booking form state
  const [formData, setFormData] = useState({
    name: '',
    phone: '',
    email: '',
    serviceTypes: [] as string[],
    nepaliDate: new NepaliDate().format('YYYY/MM/DD'),
    location: '',
    description: ''
  })
  
  // Get current Nepali date for initial state
  const now = useMemo(() => new NepaliDate(), [])
  const [currentMonth, setCurrentMonth] = useState(now.getMonth() + 1) // 1-indexed
  const [currentYear, setCurrentYear] = useState(now.getYear())

  const nepaliMonths = [
    'Baisakh', 'Jestha', 'Ashadh', 'Shrawan', 'Bhadra',
    'Ashwin', 'Kartik', 'Mangsir', 'Poush', 'Magh', 'Falgun', 'Chaitra'
  ]

  // Get days in month dynamically using the library
  const days = useMemo(() => {
    // Start at the 28th (all months have at least 28 days)
    const d = new NepaliDate(currentYear, currentMonth - 1, 28)
    let monthDays = 28
    // Increment until we hit the next month
    while (d.getMonth() === currentMonth - 1) {
      monthDays++
      d.setDate(monthDays)
    }
    return monthDays - 1
  }, [currentMonth, currentYear])

  const startDay = useMemo(() => {
    const d = new NepaliDate(currentYear, currentMonth - 1, 1)
    return d.getDay()
  }, [currentMonth, currentYear])
  
  const bookings = bookingsData || []

  const getBookingsForDate = (day: number) => {
    const dateStr = `${currentYear}/${String(currentMonth).padStart(2, '0')}/${String(day).padStart(2, '0')}`
    return bookings.filter(b => b.nepaliDate === dateStr)
  }

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Approved': return 'bg-emerald-500/80 text-amber-100'
      case 'Pending': return 'bg-gold-500/80 text-cosmic-950'
      case 'Rejected': return 'bg-red-500/80 text-amber-100'
      default: return 'bg-cosmic-700 text-amber-100'
    }
  }

  const prevMonth = () => {
    if (currentMonth === 1) {
      setCurrentMonth(12)
      setCurrentYear(currentYear - 1)
    } else {
      setCurrentMonth(currentMonth - 1)
    }
  }

  const nextMonth = () => {
    if (currentMonth === 12) {
      setCurrentMonth(1)
      setCurrentYear(currentYear + 1)
    } else {
      setCurrentMonth(currentMonth + 1)
    }
  }

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target
    setFormData({ ...formData, [name]: value })
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    
    const booking: BookingEntity = {
      id: '', // Will be generated by Firestore
      name: formData.name,
      phone: formData.phone,
      email: formData.email,
      serviceType: formData.serviceTypes.join(', '),
      nepaliDate: formData.nepaliDate,
      location: formData.location,
      description: formData.description,
      status: 'Pending',
    }

    add.mutate(booking, {
      onSuccess: () => {
        alert(t('calendar.alert.success'))
        setFormData({
          name: '',
          phone: '',
          email: '',
          serviceTypes: [],
          nepaliDate: new NepaliDate().format('YYYY/MM/DD'),
          location: '',
          description: ''
        })
      },
      onError: (error) => {
        alert(`${t('calendar.alert.error')}: ${error.message}`)
      }
    })
  }

  return (
    <div className="min-h-screen flex flex-col bg-cosmic-950 font-body">
      <Navigation />
      <main className="flex-1 py-24 relative overflow-hidden">
        <div className="absolute inset-0 bg-cosmic-gradient opacity-50"></div>
        <div className="absolute inset-0 bg-sacred-pattern"></div>
        
        <div className="relative z-10 container mx-auto px-4 max-w-6xl">
          <div className="text-center mb-12">
            <div className="w-20 h-20 mx-auto mb-8 relative">
              <div className="absolute inset-0 bg-gradient-to-br from-gold-400 to-gold-600 rounded-full animate-glow opacity-60 blur-xl"></div>
              <div className="relative w-full h-full bg-gradient-to-br from-gold-400 to-gold-600 rounded-full flex items-center justify-center text-cosmic-950 text-3xl font-display font-bold">
                ॐ
              </div>
            </div>
            <h1 className="text-5xl md:text-6xl font-display font-bold mb-4 text-gold-400">{t('home.celestialCalendar')}</h1>
            <p className="text-xl text-amber-200/70">
              {t('home.calendarDesc')}
            </p>
          </div>

          {isLoading && (
            <div className="text-center py-12">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-gold-400 mx-auto mb-4"></div>
              <p className="text-amber-200/70">Syncing with celestial alignments...</p>
            </div>
          )}

          {error && (
            <div className="text-center py-12 bg-red-900/20 rounded-2xl border border-red-500/50 mb-8">
              <p className="text-red-200">Error fetching bookings: {error.message}</p>
              <button 
                onClick={() => window.location.reload()}
                className="mt-4 px-6 py-2 bg-red-500 text-white rounded-lg hover:bg-red-600 transition-colors"
              >
                Retry
              </button>
            </div>
          )}

          {/* Calendar Navigation */}
          {!isLoading && !error && (
            <>
              <div className="bg-cosmic-800/40 backdrop-blur-sm p-6 rounded-2xl border border-gold-400/20 mb-8">
            <div className="flex justify-between items-center mb-6">
              <button
                onClick={prevMonth}
                className="px-6 py-3 bg-cosmic-900/50 border border-gold-400/30 text-amber-100 font-display font-semibold rounded-lg hover:bg-gold-400/10 hover:border-gold-400 transition-all"
              >
                {t('calendar.previous')}
              </button>
              <h2 className="text-2xl md:text-3xl font-display font-bold text-gold-400">
                {nepaliMonths[currentMonth - 1]} {currentYear} (Bikram Sambat)
              </h2>
              <button
                onClick={nextMonth}
                className="px-6 py-3 bg-cosmic-900/50 border border-gold-400/30 text-amber-100 font-display font-semibold rounded-lg hover:bg-gold-400/10 hover:border-gold-400 transition-all"
              >
                {t('calendar.next')}
              </button>
            </div>

            {/* Calendar Grid */}
            <div className="grid grid-cols-7 gap-1 md:gap-2 mb-4">
              {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(day => (
                <div key={day} className="text-center font-display font-semibold text-gold-400 p-1 md:p-2 text-xs md:text-base">
                  <span className="hidden sm:inline">{day}</span>
                  <span className="sm:hidden">{day.slice(0, 1)}</span>
                </div>
              ))}
            </div>

            <div className="grid grid-cols-7 gap-1 md:gap-2">
              {/* Empty cells for padding */}
              {Array.from({ length: startDay }, (_, i) => (
                <div key={`empty-${i}`} className="bg-transparent" />
              ))}
              {Array.from({ length: days }, (_, i) => {
                const day = i + 1
                const dayBookings = getBookingsForDate(day)
                const isToday = currentYear === now.getYear() && (currentMonth - 1) === now.getMonth() && day === now.getDate()

                return (
                  <div
                    key={day}
                    className={`bg-cosmic-900/50 border rounded-lg p-1 md:p-2 min-h-16 md:min-h-24 hover:border-gold-400/50 hover:bg-gold-400/5 cursor-pointer transition-all ${
                      isToday 
                        ? 'border-gold-400 shadow-[0_0_15px_rgba(251,191,36,0.3)] bg-gold-400/10' 
                        : 'border-gold-400/20'
                    }`}
                  >
                    <div className={`font-display font-semibold mb-1 text-sm md:text-base ${isToday ? 'text-gold-400' : 'text-amber-100'}`}>
                      {day}
                      {isToday && <span className="ml-1 text-[10px] uppercase tracking-wider text-gold-400/80 hidden sm:inline">(Today)</span>}
                    </div>
                    {dayBookings.length > 0 && (
                      <div className="space-y-1">
                        {dayBookings.map((booking, idx) => (
                          <div
                            key={idx}
                            className={`text-xs p-1 rounded font-medium ${getStatusColor(booking.status)}`}
                          >
                            {booking.serviceType}
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                )
              })}
            </div>
          </div>

          {/* Bookings List */}
          <div className="bg-cosmic-800/40 backdrop-blur-sm p-6 rounded-2xl border border-gold-400/20 mb-8">
            <h3 className="text-2xl md:text-3xl font-display font-bold mb-6 text-gold-400">{t('calendar.scheduledBookings')}</h3>
            {bookings.length === 0 ? (
              <p className="text-amber-200/60">{t('calendar.noBookings')}</p>
            ) : (
              <div className="space-y-4">
                {bookings.map((booking, index) => (
                  <div key={index} className="bg-cosmic-900/50 border border-gold-400/20 rounded-xl p-4 hover:border-gold-400/40 transition-all">
                    <div className="flex justify-between items-start mb-2">
                      <div>
                        <p className="font-display font-semibold text-amber-100">{booking.nepaliDate}</p>
                      </div>
                      <span className={`px-3 py-1 rounded-full text-sm font-display font-medium ${getStatusColor(booking.status)}`}>
                        {booking.status}
                      </span>
                    </div>
                    <p className="text-amber-200/80">{booking.serviceType}</p>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Booking Form */}
          <div className="bg-cosmic-800/40 backdrop-blur-sm p-8 rounded-2xl border border-gold-400/20 mb-8">
            <div className="text-center mb-8">
              <h3 className="text-3xl md:text-4xl font-display font-bold mb-2 text-gold-400">{t('calendar.bookAppointment')}</h3>
              <p className="text-amber-200/70">{t('calendar.fillForm')}</p>
            </div>
            
            <form onSubmit={handleSubmit} className="space-y-4" noValidate>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label htmlFor="name" className="block text-sm font-medium mb-1 text-amber-100">
                    {t('calendar.fullName')} *
                  </label>
                  <input
                    type="text"
                    id="name"
                    name="name"
                    required
                    value={formData.name}
                    onChange={handleChange}
                    className="w-full px-3 py-2 border border-gold-400/30 rounded-lg bg-cosmic-900/50 text-amber-100 placeholder-amber-200/40 focus:border-gold-400 focus:outline-none transition-colors"
                    placeholder="Your full name"
                  />
                </div>

                <div>
                  <label htmlFor="phone" className="block text-sm font-medium mb-1 text-amber-100">
                    {t('calendar.phoneNumber')} *
                  </label>
                  <input
                    type="tel"
                    id="phone"
                    name="phone"
                    required
                    value={formData.phone}
                    onChange={handleChange}
                    className="w-full px-3 py-2 border border-gold-400/30 rounded-lg bg-cosmic-900/50 text-amber-100 placeholder-amber-200/40 focus:border-gold-400 focus:outline-none transition-colors"
                    placeholder="Your phone number"
                  />
                </div>

                <div>
                  <label htmlFor="email" className="block text-sm font-medium mb-1 text-amber-100">
                    {t('calendar.email')} ({t('calendar.optional')})
                  </label>
                  <input
                    type="email"
                    id="email"
                    name="email"
                    value={formData.email}
                    onChange={handleChange}
                    className="w-full px-3 py-2 border border-gold-400/30 rounded-lg bg-cosmic-900/50 text-amber-100 placeholder-amber-200/40 focus:border-gold-400 focus:outline-none transition-colors"
                    placeholder="Your email address"
                  />
                </div>

                <div>
                  <label htmlFor="location" className="block text-sm font-medium mb-1 text-amber-100">
                    {t('calendar.location')} *
                  </label>
                  <input
                    type="text"
                    id="location"
                    name="location"
                    required
                    value={formData.location}
                    onChange={handleChange}
                    placeholder="e.g., Biratnagar, Office, or Online"
                    className="w-full px-3 py-2 border border-gold-400/30 rounded-lg bg-cosmic-900/50 text-amber-100 placeholder-amber-200/40 focus:border-gold-400 focus:outline-none transition-colors"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium mb-2 text-amber-100">
                  {t('calendar.serviceTypes')} *
                </label>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-2">
                  {serviceNames.map((service) => (
                    <label key={service} className="flex items-center space-x-2 cursor-pointer">
                      <input
                        type="checkbox"
                        value={service}
                        checked={formData.serviceTypes.includes(service)}
                        onChange={(e) => {
                          if (e.target.checked) {
                            setFormData({ ...formData, serviceTypes: [...formData.serviceTypes, service] })
                          } else {
                            setFormData({ ...formData, serviceTypes: formData.serviceTypes.filter(s => s !== service) })
                          }
                        }}
                        className="w-4 h-4 accent-gold-400"
                      />
                      <span className="text-amber-200/70 text-sm">{service}</span>
                    </label>
                  ))}
                </div>
                {formData.serviceTypes.length === 0 && (
                  <p className="text-sm text-gold-400/70 mt-1">{t('calendar.selectService')}</p>
                )}
              </div>

              <div>
                <label htmlFor="nepaliDate" className="block text-sm font-medium mb-1 text-amber-100">
                  {t('calendar.selectDate')} (BS) *
                </label>
                <NepaliDatePickerCustom
                  value={formData.nepaliDate}
                  onChange={(date) => setFormData({ ...formData, nepaliDate: date })}
                  placeholder="Select a date"
                />
                <p className="text-xs text-amber-200/50 mt-1">{t('calendar.bikramSambat')}</p>
              </div>

              <div>
                <label htmlFor="description" className="block text-sm font-medium mb-1 text-amber-100">
                  {t('calendar.description')}
                </label>
                <textarea
                  id="description"
                  name="description"
                  rows={3}
                  value={formData.description}
                  onChange={handleChange}
                  className="w-full px-3 py-2 border border-gold-400/30 rounded-lg bg-cosmic-900/50 text-amber-100 placeholder-amber-200/40 focus:border-gold-400 focus:outline-none transition-colors resize-none"
                  placeholder="Any additional information about your consultation needs"
                />
              </div>

              <button
                type="submit"
                disabled={formData.serviceTypes.length === 0}
                className="w-full bg-gradient-to-r from-gold-500 to-gold-600 text-cosmic-950 px-6 py-3 rounded-lg font-display font-semibold hover:shadow-2xl hover:shadow-gold-400/30 hover:scale-105 transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
              >
                {t('calendar.submit')}
              </button>
            </form>

            <div className="mt-6 p-4 bg-cosmic-900/50 rounded-lg border border-gold-400/20">
              <p className="text-sm text-amber-200/70">
                <strong className="text-gold-400">{t('calendar.note')}:</strong> {t('calendar.noteText')}
              </p>
            </div>
          </div>
          </>
          )}
        </div>
      </main>
      <Footer />
    </div>
  )
}
